name: Labels

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened

jobs:
  team-labels:
    runs-on: ubuntu-slim
    steps:
      - name: Add team labels
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if [[ "${{ github.event.pull_request.title }}" == D2* ]]; then
            gh pr edit ${{ github.event.pull_request.number }} --add-label "team-fun"
          fi
